### ISSUE TITLE
Wrapping issue

### ISSUE THREAD

**Issue by xaniz25** [syonfox/leaflet-panel-layers#19]
Layer Control Panel is filling up the width of the screen due to the abstract descriptions:

![wrapping](https://user-images.githubusercontent.com/46914374/68608663-af2c8480-0470-11ea-88f7-74af097d5c4f.png)

**Comment by syonfox** [comment]
It should be fixed was just a bug with not setting the default width in chrome.

**Comment by veragreen119** [comment]
This is still happening when base data layers have a tool tip. Works fine for overlay layers. It's happening in your latest example at:
To reproduce just expand base maps and hover over them.
[https://portaldev.lorrnel.com/landMap_kl/index.html](https://portaldev.lorrnel.com/landMap_kl/index.html)

**Comment by syonfox** [comment]
Ok its now fixed in the new version of leaflet panaly layers it was an issue with the style not being set properly for the base layers items

**Comment by xaniz25** [comment]
I have found another issue where when the group layer is checked before expanding then hovering, it looks like this:
 
![issue](https://user-images.githubusercontent.com/46914374/69384669-25ec2d80-0c7a-11ea-805b-0cb65f5d40bb.png)

It happens for all layers except Wildlife-Birds.
